apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  selector:
    app: whoami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  - protocol: TCP
      port: 8080
      targetPort: 8080
