apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: congtaojiang/whoami-nodejs-express:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"  # Set the expected port here
        command: ["node", "/app/server.js"]
