name: Build, Push to Docker Hub, and Deploy to EKS

on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_USERNAME }}/whoami-nodejs-express
  AWS_REGION: ap-northeast-1
  EKS_CLUSTER_NAME: k8s-cluster
  
jobs:
  build-push-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${DOCKER_HUB_REPO}:latest .
        docker push ${DOCKER_HUB_REPO}:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        sed -i 's|congtaojiang/whoami-nodejs-express|${{ env.DOCKER_HUB_REPO }}|' kubernetes/deployment.yaml
        kubectl apply -f kubernetes/deployment.yaml

    - name: Force update deployment
      run: |
        kubectl rollout restart deployment/whoami-deployment
