name: Deploy to EKS

on:
  push:
    branches: [ main ]
    paths:
      - 'kubernetes/**'

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name k8s-cluster --region ap-northeast-1
        aws eks get-token --cluster-name k8s-cluster --region ap-northeast-1
        

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml 

    - name: Wait for deployment
      run: |
        kubectl rollout status deployment/whoami-deployment
        kubectl rollout status deployment/whoami-canary 
  
  docker-push:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/congtaojiang/whoami-nodejs-express:latest .
